import Head from 'next/head'
import Image from 'next/image'
import ImageUpload from '../components/ImageUpload'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ImageUpload />
      </main>


    </div>
  )
}
